version: '3.4'

services:
  loadbalancer:
    image: adm14/loadbalancer:$BUILD_NUMBER
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    ports:
      - 9000:80

  searchapi:
    image: adm14/searchapi:$BUILD_NUMBER
    build:
      context: .
      dockerfile: SearchAPI/Dockerfile
    volumes:
      - C:/data/data.db:/data/data.db
    deploy:
        replicas: 2
    depends_on:
      - loadbalancer

  dataformatter:
    image: adm14/dataformatter:$BUILD_NUMBER
    build:
      context: .
      dockerfile: DataFormater/Dockerfile
    ports:
      - 9001:80

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  testdataformatter:
    image: ${DOCKER_REGISTRY-}testdataformatter
    build:
      context: .
      dockerfile: TestDataFormatter/Dockerfile

