version: '3.4'

services:
  loadbalancer:
    image: ${DOCKER_REGISTRY-}loadbalancer
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    ports:
      - 9000:80

  searchapi:
    image: ${DOCKER_REGISTRY-}searchapi
    build:
      context: .
      dockerfile: SearchAPI/Dockerfile
    volumes:
      - C:/data/data.db:/data/data.db
    deploy:
        replicas: 2
    depends_on:
      - loadbalancer

  dataformatter:
    image: ${DOCKER_REGISTRY-}dataformatter
    build:
      context: .
      dockerfile: DataFormater/Dockerfile
    ports:
      - 9001:80

