pipeline {
    parameters {
        string(name: 'VERSION', defaultValue: '', description: 'Version of the application')
    }

    agent any

    stages {
        stage('Rollback') {
            steps {
                bat "docker-compose -f docker-compose.yml pull adm14/loadbalancer:%VERSION%"
                bat "docker-compose -f docker-compose.yml pull adm14/searchapi:%VERSION%"
                bat "docker-compose -f docker-compose.yml pull adm14/dataformatter:%VERSION%"
                bat "docker-compose -f docker-compose.yml up -d"
            }
        }
    }
}