pipeline {
    parameters {
        string(name: 'VERSION', defaultValue: '', description: 'Version of the application')
    }

    agent any

    stages {
        stage('Rollback') {
            steps {
                bat "docker-compose -f docker-compose.yml pull loadbalancer:%VERSION%"
                bat "docker-compose -f docker-compose.yml pull searchapi:%VERSION%"
                bat "docker-compose -f docker-compose.yml pull dataformatter:%VERSION%"
                bat "docker-compose -f docker-compose.yml up -d"
            }
        }
    }
}